// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCForfL34jTy3ADeLg4uJzGue1jkaNNgjQ',
    appId: '1:916986474727:web:b29f3d905e231b88b03242',
    messagingSenderId: '916986474727',
    projectId: 'test-96fdf',
    authDomain: 'test-96fdf.firebaseapp.com',
    storageBucket: 'test-96fdf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwLYY39mkxl9B6S-hfGogLOwaJxviWeM4',
    appId: '1:916986474727:android:65c3d30b286a9a4db03242',
    messagingSenderId: '916986474727',
    projectId: 'test-96fdf',
    storageBucket: 'test-96fdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGbCnZX-x4jEq_wy4fLo7EYyDenSwfJZ0',
    appId: '1:916986474727:ios:ca1a447edddd06dbb03242',
    messagingSenderId: '916986474727',
    projectId: 'test-96fdf',
    storageBucket: 'test-96fdf.appspot.com',
    androidClientId: '916986474727-cdvbb9me108bg7o9k0coke1b36hrse3d.apps.googleusercontent.com',
    iosClientId: '916986474727-dqcputnfa4r1nisfuvm4k9pvctk9319o.apps.googleusercontent.com',
    iosBundleId: 'com.example.ms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGbCnZX-x4jEq_wy4fLo7EYyDenSwfJZ0',
    appId: '1:916986474727:ios:ca1a447edddd06dbb03242',
    messagingSenderId: '916986474727',
    projectId: 'test-96fdf',
    storageBucket: 'test-96fdf.appspot.com',
    androidClientId: '916986474727-cdvbb9me108bg7o9k0coke1b36hrse3d.apps.googleusercontent.com',
    iosClientId: '916986474727-dqcputnfa4r1nisfuvm4k9pvctk9319o.apps.googleusercontent.com',
    iosBundleId: 'com.example.ms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCForfL34jTy3ADeLg4uJzGue1jkaNNgjQ',
    appId: '1:916986474727:web:a1c1d7a5bc19592cb03242',
    messagingSenderId: '916986474727',
    projectId: 'test-96fdf',
    authDomain: 'test-96fdf.firebaseapp.com',
    storageBucket: 'test-96fdf.appspot.com',
  );

}